name: NEPSE Daily Scraper

on:
  schedule:
    - cron: '45 10 * * *'  # once per day (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Export DB to CSV
        run: |
          sqlite3 nepse.db -header -csv "SELECT * FROM market_leaders;" > nepse.csv

      - name: Commit updated database and CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git pull origin main --rebase

          git add nepse.db nepse.csv
          git commit -m "update nepse data + csv" || echo "no changes"
          git push
